#!/bin/bash

name='plg_wizory_listpipe'
version=$(grep '<version>' wizory_listpipe.xml | cut -d'>' -f2 | cut -d'<' -f1)

rm $name-*.zip

zip -r $name-$version.zip * LICENSE -x ".git/*" "composer.*" build "tests/*" "vendor/*"